const inboxCards = [
  "Don't freak out, but I just got a tattoo of your name on my lower back.",
  "It's Fridayyyy! You know what that means.",
  "I'm at the hospital.",
  "I think I just sent a nude to the family group chat.",
  "What is your Netflix password again?",
  "I'm breaking up with you.",
  "Why is there a police car outside your house?",
  "Did you really just do that?",
  "I need bail money.",
  "I just got fired. Let's get drinks.",
  "I have a confession to make...",
  "Are we still on for our date tonight?",
  "I'm outside.",
  "Can you delete my browser history?",
  "My mom wants to meet you.",
  "I think someone is in my house.",
  "You up?",
  "I'm pregnant.",
  "I just dropped my phone in the toilet.",
  "I accidentally liked your ex's photo from 2014."
];

const replyCards = [
  "New phone, who dis?",
  "That sounds like a 'you' problem.",
  "I'm literally crying right now.",
  "Sir, this is a Wendy's.",
  "I'll pretend I didn't see that.",
  "On my way! 🏃‍♂️💨",
  "Delete my number.",
  "I'm telling your mom.",
  "Send pics or it didn't happen.",
  "I'd rather eat glass.",
  "Yikes.",
  "Same.",
  "That's what she said.",
  "I'm calling the cops.",
  "You're paying for my therapy.",
  "We're done here.",
  "I love you too.",
  "Who is this?",
  "Are you drunk?",
  "Blocked and reported.",
  "Thoughts and prayers.",
  "Cool story bro.",
  "I need an adult.",
  "Let's never speak of this again.",
  "Pics or it didn't happen.",
  "My lawyer will be in touch.",
  "Can I get a rip in the chat.",
  "Oof.",
  "Unsubscribe.",
  "I am uncomfortable with our current energy."
];

module.exports = { inboxCards, replyCards };
